# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [3]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
arr_1d = np.array([1, 2, 3, 4, 5])


# Create a 2-dimensional NumPy array using np.array()
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Create a 3-dimensional Numpy array using np.array()
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
# Shape (number of elements along each dimension)
shape = arr_1d.shape

# Number of dimensions
ndim = arr_1d.ndim

# Data type
dtype = arr_1d.dtype

# Size (total number of elements)
size = arr_1d.size

# Type of the array
arrayType = type(arr_1d)

print("1-D Array:")
print("Shape:", shape)
print("Number of Dimensions:", ndim)
print("Data Type:", dtype)
print("Size:", size)
print("Type:", arrayType)

1-D Array:
Shape: (5,)
Number of Dimensions: 1
Data Type: int64
Size: 5
Type: <class 'numpy.ndarray'>


In [6]:
# Attributes of 2-dimensional array
shape = arr_2d.shape

# Number of dimensions
ndim = arr_2d.ndim

# Data type
dtype = arr_2d.dtype

# Size (total number of elements)
size = arr_2d.size

# Type of the array
arrayType = type(arr_2d)

print("1-D Array:")
print("Shape:", shape)
print("Number of Dimensions:", ndim)
print("Data Type:", dtype)
print("Size:", size)
print("Type:", arrayType)

1-D Array:
Shape: (3, 3)
Number of Dimensions: 2
Data Type: int64
Size: 9
Type: <class 'numpy.ndarray'>


In [7]:
# Attributes of 3-dimensional array
shape = arr_3d.shape

# Number of dimensions
ndim = arr_3d.ndim

# Data type
dtype = arr_3d.dtype

# Size (total number of elements)
size = arr_3d.size

# Type of the array
arrayType = type(arr_3d)

print("1-D Array:")
print("Shape:", shape)
print("Number of Dimensions:", ndim)
print("Data Type:", dtype)
print("Size:", size)
print("Type:", arrayType)

1-D Array:
Shape: (2, 2, 2)
Number of Dimensions: 3
Data Type: int64
Size: 8
Type: <class 'numpy.ndarray'>


In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(arr_2d)
df


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [11]:
# Create an array of shape (10, 2) with only ones
ones_2d = np.ones((10,2))
ones_2d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_3d = np.zeros((7,2,3))
zeros_3d

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Create an array within a range of 0 and 100 with step 3
arr = np.arange(0,100,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [18]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rndArr = np.random.randint(0,10,size=(7,2))
rndArr

array([[7, 9],
       [9, 1],
       [9, 3],
       [6, 0],
       [8, 1],
       [4, 5],
       [2, 3]])

In [20]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rndFloats = np.random.rand(3,5)
rndFloats

array([[0.39089907, 0.13846042, 0.32351256, 0.24023283, 0.94117772],
       [0.9542457 , 0.13052647, 0.0190517 , 0.77680631, 0.04665284],
       [0.21815096, 0.78621325, 0.77211159, 0.43891194, 0.01634923]])

In [25]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rndArr = np.random.randint(0,10,size=(4,6))
rndArr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is? **The numbers stay the same, because we pass a fixed seed, if we changed the seed we would get different numbers every execution.**


In [28]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rndArr = np.random.randint(1,10,size=(3,7))
print(rndArr)

# Find the unique numbers in the array you just created
unique_numbers = np.unique(rndArr)
unique_numbers

[[2 5 8 9 9 1 9]
 [7 9 8 1 8 8 3]
 [1 8 3 3 1 5 7]]


array([1, 2, 3, 5, 7, 8, 9])

In [29]:
# Find the 0'th index of the latest array you created
print(rndArr[0][0])

2


In [30]:
# Get the first 2 rows of latest array you created
print(rndArr[:2,:])

[[2 5 8 9 9 1 9]
 [7 9 8 1 8 8 3]]


In [31]:
# Get the first 2 values of the first 2 rows of the latest array
rndArr[:2,:2]

array([[2, 5],
       [7, 9]])

In [33]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rndArr = np.random.randint(0,10,size=(3,5))
ones = np.ones((3,5))

In [34]:
# Add the two arrays together
print(ones+rndArr)

[[10.  9.  7.  9.  8.]
 [ 2.  1.  7.  7.  8.]
 [ 5.  3.  8.  6.  3.]]


In [ ]:
# Create another array of ones of shape (5, 3)
ones_5_3 = np.ones(5,3)

In [35]:
# Try add the array of ones and the other most recent array together
print(ones+ones_5_3)

NameError: ignored

When you try the last cell, it produces an error. Why do think this is?
**because the 2 arrays are of two different dimensions**

How would you fix it?**by transposing one of the two**

In [39]:
# Create another array of ones of shape (3, 5)
onesAgain = np.ones((3,5))

In [43]:
# Subtract the new array of ones from the other most recent array
print(rndArr - ones)

[[ 8.  7.  5.  7.  6.]
 [ 0. -1.  5.  5.  6.]
 [ 3.  1.  6.  4.  1.]]


In [44]:
# Multiply the ones array with the latest array
print(rndArr*ones)

[[9. 8. 6. 8. 7.]
 [1. 0. 6. 6. 7.]
 [4. 2. 7. 5. 2.]]


In [45]:
# Take the latest array to the power of 2 using '**'
print(rndArr**2)

[[81 64 36 64 49]
 [ 1  0 36 36 49]
 [16  4 49 25  4]]


In [46]:
# Do the same thing with np.square()  --> Yes
print(np.square(rndArr))

[[81 64 36 64 49]
 [ 1  0 36 36 49]
 [16  4 49 25  4]]


In [47]:
# Find the mean of the latest array using np.mean()
print(np.mean(rndArr))

5.2


In [48]:
# Find the maximum of the latest array using np.max()
print(np.max(rndArr))

9


In [49]:
# Find the minimum of the latest array using np.min()
print(np.min(rndArr))

0


In [50]:
# Find the standard deviation of the latest array
print(np.std(rndArr))

2.6882460204874605


In [51]:
# Find the variance of the latest array
print(np.var(rndArr))

7.2266666666666675


In [52]:
# Reshape the latest array to (3, 5, 1)
print(np.reshape(rndArr,(3,5,1)))

[[[9]
  [8]
  [6]
  [8]
  [7]]

 [[1]
  [0]
  [6]
  [6]
  [7]]

 [[4]
  [2]
  [7]
  [5]
  [2]]]


In [53]:
# Transpose the latest array
print(np.transpose(rndArr))

[[9 1 4]
 [8 0 2]
 [6 6 7]
 [8 6 5]
 [7 7 2]]


What does the transpose do?
**it reverse the dimensions of the 2d array, if it was x*y it will be y*x**

In [55]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr_3_3 = np.random.randint(0,10,size=(3,3))
arr_3_2 = np.random.randint(0,10,size=(3,2))


In [56]:
# Perform a dot product on the two newest arrays you created
print(np.dot(arr_3_3,arr_3_2))

[[47 51]
 [69 87]
 [47 77]]


In [59]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
firstArr_4_3 = np.random.randint(0,10,size=(4,3))
secondArr_4_3 = np.random.randint(0,10,size=(4,3))

In [60]:
# Perform a dot product on the two newest arrays you created
print(np.dot(firstArr_4_3,secondArr_4_3))

ValueError: ignored

It doesn't work. How would you fix it?  **because the number of columns of the first array must equal the number of rows of the second array**

In [64]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both

print(np.dot(firstArr_4_3,np.transpose(secondArr_4_3)))


[[49 46 54 31]
 [30 44 32 26]
 [57 51 65 36]
 [55 32 56 23]]


Notice how performing a transpose allows the dot product to happen.

Why is this?
**as the transpose made the number of columns of the first array  equal the number of rows of the second array **

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [67]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
firstArr_4_3 = np.random.randint(0,10,size=(4,3))
secondArr_4_3 = np.random.randint(0,10,size=(4,3))


In [68]:
# Compare the two arrays with '>'
print(firstArr_4_3>secondArr_4_3)

[[ True  True  True]
 [False False False]
 [False  True False]
 [ True False  True]]


What happens when you compare the arrays with `>`? **every number in  the first array is compared to the corresponding one in the other array**

In [69]:
# Compare the two arrays with '>='
print(firstArr_4_3 >= secondArr_4_3)

[[ True  True  True]
 [False False False]
 [ True  True False]
 [ True False  True]]


In [71]:
# Find which elements of the first array are greater than 7
print(firstArr_4_3[firstArr_4_3 > 7])
print(firstArr_4_3>7)

[8 8]
[[False  True  True]
 [False False False]
 [False False False]
 [False False False]]


In [72]:
# Which parts of each array are equal? (try using '==')
print(firstArr_4_3 == secondArr_4_3)

[[False False False]
 [False False False]
 [ True False False]
 [False False False]]


In [73]:
# Sort one of the arrays you just created in ascending order
print(np.sort(firstArr_4_3))

[[6 8 8]
 [2 2 2]
 [3 5 7]
 [0 7 7]]


In [74]:
# Sort the indexes of one of the arrays you just created
print(np.argsort(firstArr_4_3))

[[0 1 2]
 [0 1 2]
 [0 2 1]
 [1 0 2]]


In [75]:
# Find the index with the maximum value in one of the arrays you've created
print(np.argmax(firstArr_4_3))

1


In [76]:
# Find the index with the minimum value in one of the arrays you've created
print(np.argmin(firstArr_4_3))

10


In [77]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
print(np.argmax(firstArr_4_3,axis=1))

[1 0 1 0]


In [78]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
print(np.argmin(firstArr_4_3,axis=0))

[1 3 1]


In [79]:
# Create an array of normally distributed random numbers
randomArr = np.random.normal(0,1,10)
randomArr

array([ 0.17483301, -1.21685489,  1.04934739,  1.32510566,  0.73450106,
       -0.95449726, -0.75117942, -1.13042805,  0.76997736,  1.26838952])

In [80]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenlySpaced = np.linspace(1,100,10)
evenlySpaced

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.